### ISSUE TITLE
Single token refresh does not behave as described

### ISSUE THREAD

**Issue by jckw** [flavors/django-graphql-jwt#91]
As discussed here https://github.com/flavors/django-graphql-jwt/issues/2#issuecomment-424451507, if `RefreshToken` is called after `JWT_EXPIRATION_DELTA`, an error is returned.

This makes `JWT_REFRESH_EXPIRATION_DELTA` redundant, since after `JWT_EXPIRATION_DELTA`, the token cannot be refreshed. 

This behaviour is [in conflict with the docs](https://django-graphql-jwt.domake.io/en/stable/refresh_token.html#queries) that seem to suggest (in the diagrams) that refreshing a token can still be done _after_ `JWT_EXPIRATION_DELTA`. This makes a lot more sense than the current behaviour. 

### Possible cause
This is likely due to the `get_payload` function [not making a distinction between tokens that have `JWT_EXPIRATION_DELTA` and those that have reached `JWT_REFRESH_EXPIRATION_DELTA`](https://github.com/flavors/django-graphql-jwt/blob/0e71fa59b18b11db2a122cd2b88dcd29e241ab18/graphql_jwt/utils.py#L86).

This seems like the bug, since it makes single token refresh pretty useless unless the client sends a refresh token every 5 minutes (or whatever  `JWT_EXPIRATION_DELTA` is set to) regardless. That means that clients who are not active for more than 5 minutes will have to log in again, which isn't how JWT usually works.

Instead, `JWT_REFRESH_EXPIRED_HANDLER` is called _after_ `get_payload`.

Therefore the "Refresh has expired" exception can never be raised since "Signature has expired" will be raised first (as the refresh delta is usually longer than the expiration delta).

### Possible fix
`get_payload` should not raise any errors until the `JWT_REFRESH_EXPIRED_HANDLER` has been called.

**Comment by jckw** [comment]
A better fix may be that in when a refresh is called,  `JSONWebTokenExpired` is ignored when calling `get_payload`.

Since a payload isn't returned if the token has expired (since an error is raised by PyJWT), this would have to be done by modifying the args in the JWT_DECODE_HANDLER.

`get_payload` would have some override args that get passed to JWT_DECODE_HANDLER and override the `jwt_settings.JWT_VERIFY_EXPIRATION`. 

E.g. In `utils`:

```
def get_payload(token, context=None, refresh=False):
    try:
        payload = jwt_settings.JWT_DECODE_HANDLER(token, context, refresh)
    except ...
    return payload
```

```
def jwt_decode(token, context=None, refresh=False):
    return jwt.decode(
        ...
        options={
            'verify_exp': False if refresh else jwt_settings.JWT_VERIFY_EXPIRATION,
        },
        ...)
```

And then in `mixins`:

```
class KeepAliveRefreshMixin(object):
    ...
    def refresh(cls, root, info, token, **kwargs):
        context = info.context
        payload = get_payload(token, context, refresh=True)
        ...
```

An expired signature should not prevent users _trying to_ refresh a token, so this should be fine.

**Comment by jckw** [comment]
In case this is an issue, and other people come across it: here's a patch.

```
"""
A kind of monkey patch for 'django-graphql-jwt' until https://github.com/flavors/django-graphql-jwt/issues/91 is resolved.
"""
from django.utils.translation import ugettext as _
import jwt
import graphene
from graphene.types.generic import GenericScalar
from graphql_jwt.settings import jwt_settings
from graphql_jwt import exceptions
from graphql_jwt.utils import get_user_by_payload
from graphql_jwt.mixins import RefreshTokenMixin, JSONWebTokenMixin
from graphql_jwt.decorators import setup_jwt_cookie


def jwt_decode(token, context=None, refresh=False):
    return jwt.decode(
        token,
        jwt_settings.JWT_SECRET_KEY,
        jwt_settings.JWT_VERIFY,
        options={
            'verify_exp': False if refresh else jwt_settings.JWT_VERIFY_EXPIRATION,
        },
        leeway=jwt_settings.JWT_LEEWAY,
        audience=jwt_settings.JWT_AUDIENCE,
        issuer=jwt_settings.JWT_ISSUER,
        algorithms=[jwt_settings.JWT_ALGORITHM])


def get_payload(token, context=None, refresh=False):
    try:
        payload = jwt_decode(token, context, refresh)
    except jwt.ExpiredSignature:
        raise exceptions.JSONWebTokenExpired()
    except jwt.DecodeError:
        raise exceptions.JSONWebTokenError(_('Error decoding signature'))
    except jwt.InvalidTokenError:
        raise exceptions.JSONWebTokenError(_('Invalid token'))
    return payload


class KeepAliveRefreshMixin(object):

    class Fields:
        token = graphene.String(required=True)

    @classmethod
    @setup_jwt_cookie
    def refresh(cls, root, info, token, **kwargs):
        context = info.context
        payload = get_payload(token, context, refresh=True)
        user = get_user_by_payload(payload)
        orig_iat = payload.get('origIat')

        if not orig_iat:
            raise exceptions.JSONWebTokenError(_('origIat field is required'))

        if jwt_settings.JWT_REFRESH_EXPIRED_HANDLER(orig_iat, context):
            raise exceptions.JSONWebTokenError(_('Refresh has expired'))

        payload = jwt_settings.JWT_PAYLOAD_HANDLER(user, context)
        payload['origIat'] = orig_iat

        token = jwt_settings.JWT_ENCODE_HANDLER(payload, context)
        return cls(token=token, payload=payload)


class RefreshMixin((RefreshTokenMixin
                    if jwt_settings.JWT_LONG_RUNNING_REFRESH_TOKEN
                    else KeepAliveRefreshMixin),
                   JSONWebTokenMixin):

    payload = GenericScalar()


class Refresh(RefreshMixin, graphene.Mutation):

    class Arguments(RefreshMixin.Fields):
        """Refresh Arguments"""

    @classmethod
    def mutate(cls, *arg, **kwargs):
        return cls.refresh(*arg, **kwargs)
```

**Comment by mongkok** [comment]
Hi @jckw and I'm sorry for the delay in my response.

Let me just clarify this:
- If `verifyToken` is called after `JWT_EXPIRATION_DELTA` an error is returned, but `refreshToken` is available.
- If `refreshToken` is called after `JWT_REFRESH_EXPIRATION_DELTA` an error is returned.

See also: https://django-graphql-jwt.domake.io/en/stable/refresh_token.html

I close the issue, if you have any questions please let me know.

**Comment by themotu** [comment]
@mongkok There is definitely a bug here as refreshToken doesn't work as intended in docs.

```Python
GRAPHQL_JWT = {
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_EXPIRATION_DELTA': timedelta(minutes=1),
    'JWT_REFRESH_EXPIRATION_DELTA': timedelta(days=7),
}
```

Tested Scenario 1:

1. Login get token
2. wait 1 minute
3. Attempt refresh
Result: `"message": "Signature has expired",`

Tested Scenario 2:

1. Login get token
2. wait 1 minute
3. Attempt verify
4. Attempt refresh
Result: `"message": "Signature has expired",`


**Expected behavior:**

1. Login get token
2. wait 1 minute
3. Attempt refresh
Result: Get new token

**Comment by themotu** [comment]
I have fixed this to be as described in the documentation and submitted a PR. This is a rather trivial fix but does match the expected behavior. I have tested this and it does work. #116

**Comment by coffeepy** [comment]
Im still seeing this issue sadly in 0.3.4, was this resolved?
